@echo off
setlocal EnableExtensions DisableDelayedExpansion
chcp 65001 >nul
title Git Bootstrap Auto Remote

set "GITHUB_OWNER=needsleepz"
set "DEFAULT_NAME=needsleepz"
set "DEFAULT_EMAIL=145240620+needsleepz@users.noreply.github.com"

for %%I in ("%CD%") do set "FOLDER_NAME=%%~nxI"
set "AUTO_REMOTE=https://github.com/%GITHUB_OWNER%/%FOLDER_NAME%.git"

echo ============================================================
echo  Git Bootstrap Auto Remote for Windows
echo  Run this file inside your project root folder.
echo  It auto-guesses GitHub remote from the folder name.
echo  It will NOT force push and will NOT delete your files.
echo ============================================================
echo.
echo Current folder:
echo %CD%
echo.
echo Auto remote guess:
echo %AUTO_REMOTE%
echo.

where git >nul 2>nul
if errorlevel 1 (
    echo [ERROR] Git was not found in PATH.
    echo Install Git for Windows first: https://git-scm.com/download/win
    pause
    exit /b 1
)

set /p CONFIRM=Use this folder as the Git project root? Type Y to continue: 
if /I not "%CONFIRM%"=="Y" (
    echo Cancelled.
    pause
    exit /b 0
)

echo.
echo [1/8] Checking Git repository...
if exist ".git" (
    echo Existing .git folder found. Using current repository.
) else (
    git init
    if errorlevel 1 (
        echo [ERROR] git init failed.
        pause
        exit /b 1
    )
)

git branch -M main >nul 2>nul

echo.
echo [2/8] Setting Git identity for this project...
set /p GIT_NAME=Git user.name [%DEFAULT_NAME%]: 
if "%GIT_NAME%"=="" set "GIT_NAME=%DEFAULT_NAME%"

set /p GIT_EMAIL=Git user.email [%DEFAULT_EMAIL%]: 
if "%GIT_EMAIL%"=="" set "GIT_EMAIL=%DEFAULT_EMAIL%"

git config user.name "%GIT_NAME%"
git config user.email "%GIT_EMAIL%"
git config core.autocrlf false

echo.
echo [3/8] Creating/updating .gitattributes...
if not exist ".gitattributes" (
    (
        echo * text=auto eol=lf
        echo.
        echo *.bat text eol=crlf
        echo *.cmd text eol=crlf
        echo *.ps1 text eol=crlf
        echo.
        echo *.png binary
        echo *.jpg binary
        echo *.jpeg binary
        echo *.gif binary
        echo *.webp binary
        echo *.ico binary
        echo *.zip binary
        echo *.7z binary
        echo *.rar binary
    ) > ".gitattributes"
) else (
    findstr /C:"* text=auto eol=lf" ".gitattributes" >nul 2>nul
    if errorlevel 1 (
        (
            echo.
            echo # === Auto-generated by Git Bootstrap Auto Remote ===
            echo * text=auto eol=lf
            echo *.bat text eol=crlf
            echo *.cmd text eol=crlf
            echo *.ps1 text eol=crlf
        ) >> ".gitattributes"
    )
)

echo.
echo [4/8] Creating/updating .gitignore...
if not exist ".gitignore" type nul > ".gitignore"

findstr /C:"# === Git Bootstrap Auto Remote safe ignores ===" ".gitignore" >nul 2>nul
if errorlevel 1 (
    (
        echo.
        echo # === Git Bootstrap Auto Remote safe ignores ===
        echo .DS_Store
        echo Thumbs.db
        echo .env
        echo .env.*
        echo !.env.example
        echo *.log
        echo logs/
        echo node_modules/
        echo dist/
        echo build/
        echo .cache/
        echo .vite/
        echo .next/
        echo .nuxt/
        echo vendor/
        echo .idea/
        echo *.user
        echo *.suo
        echo bin/
        echo obj/
        echo publish/
        echo .playwright-mcp/
        echo test-results/
        echo playwright-report/
        echo blob-report/
        echo *.bak
        echo *.old
        echo *.tmp
        echo *.backup
    ) >> ".gitignore"
)

echo.
echo [5/8] Creating VS Code UTF-8 settings...
if not exist ".vscode" mkdir ".vscode"
if not exist ".vscode\settings.json" (
    (
        echo {
        echo   "files.encoding": "utf8",
        echo   "files.autoGuessEncoding": false,
        echo   "files.eol": "\n",
        echo   "files.insertFinalNewline": true,
        echo   "files.trimTrailingWhitespace": true,
        echo   "editor.renderWhitespace": "boundary"
        echo }
    ) > ".vscode\settings.json"
) else (
    echo .vscode\settings.json already exists. Not overwriting it.
)

echo.
echo [6/8] Creating Codex project instructions...
if not exist "AGENTS.md" (
    (
        echo # Project rules for Codex
        echo.
        echo - Always preserve Thai text and emoji as UTF-8.
        echo - Never rewrite text through ANSI, latin1, cp1252, cp874, TIS-620, or Windows default encoding.
        echo - Do not replace readable text with question marks.
        echo - Do not rewrite entire files unless explicitly requested.
        echo - Prefer small, targeted patches.
        echo - Before editing, run git status.
        echo - After editing, run git diff.
        echo - Do not use PowerShell Set-Content or Out-File without -Encoding utf8.
    ) > "AGENTS.md"
) else (
    echo AGENTS.md already exists. Not overwriting it.
)

echo.
echo [7/8] Staging files...
git add --renormalize .
git add .

echo.
echo Git status:
git status --short
echo.

set /p DO_COMMIT=Create a commit now? Type Y to commit: 
if /I "%DO_COMMIT%"=="Y" (
    set /p COMMIT_MSG=Commit message [Initial project snapshot]: 
    if "%COMMIT_MSG%"=="" set "COMMIT_MSG=Initial project snapshot"

    git diff --cached --quiet
    if not errorlevel 1 (
        echo Nothing staged to commit.
    ) else (
        git commit -m "%COMMIT_MSG%"
        if errorlevel 1 (
            echo [ERROR] Commit failed.
            pause
            exit /b 1
        )
    )
) else (
    echo Skipped commit.
)

echo.
echo [8/8] Auto GitHub remote / push
echo Suggested remote:
echo %AUTO_REMOTE%
echo.
set /p REMOTE_URL=Remote URL [Enter = use suggested, N = skip, or paste custom URL]: 

if /I "%REMOTE_URL%"=="N" (
    echo Skipped remote setup.
    goto :done
)

if "%REMOTE_URL%"=="" set "REMOTE_URL=%AUTO_REMOTE%"

git remote get-url origin >nul 2>nul
if errorlevel 1 (
    git remote add origin "%REMOTE_URL%"
) else (
    git remote set-url origin "%REMOTE_URL%"
)

echo.
echo Remote now:
git remote -v
echo.
echo Push options:
echo   1 = git push -u origin main
echo   2 = git push -u origin main:recovered-local
echo   0 = skip push
set /p PUSH_OPT=Choose [0/1/2]: 

if "%PUSH_OPT%"=="1" (
    git push -u origin main
) else if "%PUSH_OPT%"=="2" (
    git push -u origin main:recovered-local
) else (
    echo Skipped push.
)

:done
echo.
echo ============================================================
echo Done.
echo Useful next commands:
echo   git status
echo   git log --oneline -5
echo   git push
echo ============================================================
pause
endlocal
