@echo off
setlocal EnableExtensions DisableDelayedExpansion
chcp 65001 >nul
title Roblox-AntiAFK - Git Bootstrap

echo ============================================================
echo  Roblox-AntiAFK - Git Bootstrap for Windows
echo  Run this file inside your project root folder.
echo  It will NOT force push and will NOT delete your files.
echo ============================================================
echo.

where git >nul 2>nul
if errorlevel 1 (
    echo [ERROR] Git was not found in PATH.
    echo Install Git for Windows first: https://git-scm.com/download/win
    pause
    exit /b 1
)

echo Current folder:
echo %CD%
echo.
set /p CONFIRM=Use this folder as the Git project root? Type Y to continue: 
if /I not "%CONFIRM%"=="Y" (
    echo Cancelled.
    pause
    exit /b 0
)

echo.
echo [1/7] Checking Git repository...
if exist ".git" (
    echo Existing .git folder found. Using current repository.
) else (
    git init
    if errorlevel 1 (
        echo [ERROR] git init failed.
        pause
        exit /b 1
    )
)

git branch -M main >nul 2>nul

echo.
echo [2/7] Setting Git identity for this project...
set "DEFAULT_NAME=needsleepz"
set "DEFAULT_EMAIL=145240620+needsleepz@users.noreply.github.com"

set /p GIT_NAME=Git user.name [%DEFAULT_NAME%]: 
if "%GIT_NAME%"=="" set "GIT_NAME=%DEFAULT_NAME%"

set /p GIT_EMAIL=Git user.email [%DEFAULT_EMAIL%]: 
if "%GIT_EMAIL%"=="" set "GIT_EMAIL=%DEFAULT_EMAIL%"

git config user.name "%GIT_NAME%"
git config user.email "%GIT_EMAIL%"
git config core.autocrlf false

echo.
echo [3/7] Creating/updating .gitattributes...
if not exist ".gitattributes" (
    (
        echo * text=auto eol=lf
        echo.
        echo *.bat text eol=crlf
        echo *.cmd text eol=crlf
        echo *.ps1 text eol=crlf
        echo.
        echo *.png binary
        echo *.ico binary
    ) > ".gitattributes"
) else (
    findstr /C:"* text=auto eol=lf" ".gitattributes" >nul 2>nul
    if errorlevel 1 (
        (
            echo.
            echo # === Auto-generated by git_bootstrap_windows ===
            echo * text=auto eol=lf
            echo *.bat text eol=crlf
            echo *.cmd text eol=crlf
            echo *.ps1 text eol=crlf
        ) >> ".gitattributes"
    )
)

echo.
echo [4/7] Creating/updating .gitignore...
if not exist ".gitignore" type nul > ".gitignore"

findstr /C:"# === Roblox-AntiAFK ===" ".gitignore" >nul 2>nul
if errorlevel 1 (
    (
        echo.
        echo # === Roblox-AntiAFK ===
        echo .DS_Store
        echo Thumbs.db
        echo .vscode/
        echo .idea/
        echo *.user
        echo *.suo
        echo bin/
        echo obj/
        echo publish/
        echo *.log
        echo *.bak
        echo *.old
        echo *.tmp
    ) >> ".gitignore"
)

echo.
echo [5/7] Creating VS Code settings...
if not exist ".vscode" mkdir ".vscode"
if not exist ".vscode\settings.json" (
    (
        echo {
        echo   "files.encoding": "utf8",
        echo   "files.autoGuessEncoding": false,
        echo   "files.eol": "\n",
        echo   "files.insertFinalNewline": true,
        echo   "files.trimTrailingWhitespace": true,
        echo   "editor.renderWhitespace": "boundary",
        echo   "editor.tabSize": 4,
        echo   "editor.insertSpaces": true,
        echo   "[csharp]": {
        echo     "editor.tabSize": 4,
        echo     "editor.insertSpaces": true
        echo   }
        echo }
    ) > ".vscode\settings.json"
) else (
    echo .vscode\settings.json already exists. Not overwriting it.
)

echo.
echo [6/7] Staging files...
git add --renormalize .
git add .

echo.
echo Git status:
git status --short
echo.

set /p DO_COMMIT=Create a commit now? Type Y to commit: 
if /I not "%DO_COMMIT%"=="Y" (
    echo Skipped commit.
    goto :push_setup
)

set /p COMMIT_MSG=Commit message: 
if "%COMMIT_MSG%"=="" set "COMMIT_MSG=Initial commit"

git diff --cached --quiet
if not errorlevel 1 (
    echo Nothing staged to commit.
) else (
    git commit -m "%COMMIT_MSG%"
    if errorlevel 1 (
        echo [ERROR] Commit failed.
        pause
        exit /b 1
    )
)

:push_setup
echo.
echo [7/7] Optional GitHub remote / push
git remote -v
echo.
set /p REMOTE_URL=GitHub remote URL, blank to skip: 
if "%REMOTE_URL%"=="" (
    echo Skipped remote setup.
    goto :done
)

git remote get-url origin >nul 2>nul
if errorlevel 1 (
    git remote add origin "%REMOTE_URL%"
) else (
    git remote set-url origin "%REMOTE_URL%"
)

echo.
echo Push options:
echo   1 = git push -u origin main
echo   0 = skip push
set /p PUSH_OPT=Choose [0/1]: 

if "%PUSH_OPT%"=="1" (
    git push -u origin main
) else (
    echo Skipped push.
)

:done
echo.
echo ============================================================
echo Done.
echo Useful next commands:
echo   git status
echo   git log --oneline -5
echo   git push
echo ============================================================
pause
endlocal
